language: node_js
node_js:
  - 12
branches:
  only:
    - master
jobs:
  include:
    - stage: Test
      script: npm test
      script: npm run lint
    - stage: Deploy
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true,
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./public
        repo: theimpressionist/theimpressionist.github.io
        on:
          branch: master
stages:
  - Test
  - name: Deploy
    if: branch = master