language: node_js
node_js:
  - 12
branches:
  only:
    - master
jobs:
  include:
    - stage: Setup
      script: npm i
    - stage: Test
      script: npm test
    - stage: Lint
      script: npm run lint
    - stage: Build
      script: npm run build
    - stage: Deploy
      deploy:
        provider: pages
        skip_cleanup: true,
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./public
        repo: theimpressionist/theimpressionist.github.io
        on:
          branch: master
  